from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class Entry:
    term: str
    category: str
    meaning: str
    example: str
    related: tuple[str, ...] = ()
    aliases: tuple[str, ...] = ()
    why_it_matters: str = ""


ENTRIES = (
    Entry("Agent", "Agents", "Software that uses a model to choose and perform actions toward a goal.", "A support agent reads a ticket, checks an order, and drafts a reply.", ("Tool use", "Planning", "LLM")),
    Entry("Alignment", "Security", "Making an AI system behave in ways consistent with intended goals and human values.", "Training a chatbot to be helpful while refusing unsafe requests.", ("RLHF", "Guardrails")),
    Entry("Artificial General Intelligence (AGI)", "Foundations", "A hypothetical system able to learn and perform across most intellectual tasks at human level or beyond.", "AGI is a research goal, not a capability current models are known to possess.", ("Narrow AI",)),
    Entry("Attention", "Models", "A mechanism that lets a model weigh which parts of its input matter most for each output.", "While translating a pronoun, attention can emphasize the noun it refers to.", ("Transformer", "Context window")),
    Entry("Autoencoder", "Models", "A network trained to compress data into a representation and reconstruct the original input.", "An autoencoder can learn compact features from images.", ("Embedding", "Latent space")),
    Entry("Backpropagation", "Training", "The algorithm used to calculate how each model parameter contributed to an error.", "A network propagates loss backward before updating its weights.", ("Gradient descent", "Loss function")),
    Entry("Benchmark", "Evaluation", "A standardized dataset and procedure used to compare model performance.", "MMLU compares language models across many academic subjects.", ("Evaluation", "Metric")),
    Entry("Chain of Thought", "Prompting", "Intermediate reasoning steps produced before a model gives its final answer.", "A model works through a word problem step by step.", ("Prompt", "Reasoning model")),
    Entry("Chunking", "Retrieval", "Splitting documents into smaller passages that can be indexed and retrieved.", "A handbook is divided into 500-token sections for search.", ("RAG", "Embedding")),
    Entry("Classification", "Tasks", "Assigning an input to one or more predefined labels.", "Marking an email as spam or not spam.", ("Supervised learning",)),
    Entry("Context Window", "Models", "The maximum amount of input and generated text a model can consider at once.", "A 32K-token model can process a medium-length report in one request.", ("Token", "Attention")),
    Entry("Diffusion Model", "Models", "A generative model that learns to turn noise into structured data through repeated denoising.", "An image generator gradually converts random noise into a photograph.", ("Generative AI", "Latent space")),
    Entry("Distillation", "Training", "Training a smaller model to imitate a larger, more capable teacher model.", "A compact model learns from outputs generated by a large model.", ("Quantization", "Fine-tuning")),
    Entry("Embedding", "Retrieval", "A numeric vector representing the meaning or features of data.", "Similar support questions have embeddings that are close together.", ("Vector database", "Semantic search")),
    Entry("Epoch", "Training", "One complete pass through the training dataset.", "Training for five epochs means the model sees every example five times.", ("Batch", "Fine-tuning")),
    Entry("Few-shot Prompting", "Prompting", "Providing a model with a small number of examples in the prompt.", "Two labeled reviews show the model how to classify a third.", ("Zero-shot", "Prompt")),
    Entry("Fine-tuning", "Training", "Further training a pretrained model on narrower data for a specific behavior or domain.", "A general language model is fine-tuned on legal documents.", ("Pretraining", "LoRA")),
    Entry("Foundation Model", "Foundations", "A broadly trained model that can be adapted to many downstream tasks.", "A language model is reused for summarization, search, and coding.", ("Pretraining", "Fine-tuning")),
    Entry("Generative AI", "Foundations", "AI that creates new content such as text, images, audio, video, or code.", "A model writes a product description from bullet points.", ("LLM", "Diffusion model")),
    Entry("Gradient Descent", "Training", "An optimization method that adjusts parameters in the direction that reduces error.", "Each training step nudges model weights toward a lower loss.", ("Backpropagation", "Learning rate")),
    Entry("Guardrails", "Security", "Rules and technical controls that constrain model inputs, outputs, or actions.", "A filter blocks personal data from being included in responses.", ("Alignment", "Grounding")),
    Entry("Hallucination", "Reliability", "A fluent but unsupported or incorrect model output.", "A chatbot invents a journal article that does not exist.", ("Grounding", "RAG")),
    Entry("Inference", "Operations", "Running a trained model to produce a prediction or output.", "Generating a summary from a report is an inference request.", ("Latency", "Training")),
    Entry("Large Language Model (LLM)", "Models", "A model trained on large text collections to understand and generate language.", "An LLM can summarize documents or answer questions in natural language.", ("Transformer", "Token")),
    Entry("Latency", "Operations", "The time between sending a request and receiving a response.", "Streaming makes the first words appear before the full answer is ready.", ("Inference", "Throughput")),
    Entry("Learning Rate", "Training", "A setting controlling the size of each parameter update during training.", "A rate that is too high can make training unstable.", ("Gradient descent", "Hyperparameter")),
    Entry("LoRA", "Training", "Low-Rank Adaptation, an efficient way to fine-tune a model by training small added matrices.", "A team customizes an LLM without updating all of its original weights.", ("Fine-tuning", "PEFT")),
    Entry("Loss Function", "Training", "A formula measuring how far a model's prediction is from the desired result.", "Cross-entropy loss penalizes incorrect class probabilities.", ("Backpropagation", "Gradient descent")),
    Entry("Machine Learning", "Foundations", "Methods that learn patterns from data instead of relying only on explicit rules.", "A fraud detector learns signals from past transactions.", ("Deep learning", "Supervised learning")),
    Entry("Model", "Foundations", "A learned mathematical system that maps inputs to predictions or generated outputs.", "A vision model maps image pixels to object labels.", ("Training", "Inference")),
    Entry("Multimodal", "Models", "Able to process or generate more than one kind of data, such as text, images, or audio.", "A model answers questions about an uploaded chart.", ("Vision-language model",)),
    Entry("Neural Network", "Models", "A layered computational model whose connected parameters learn patterns from data.", "A network learns to identify handwritten digits.", ("Deep learning", "Parameter")),
    Entry("Overfitting", "Training", "Learning the training examples too specifically, causing poor performance on new data.", "A classifier scores perfectly in training but fails on unseen samples.", ("Regularization", "Validation set")),
    Entry("Parameter", "Models", "A learned numeric value inside a model that shapes its behavior.", "Training changes billions of weights in a large language model.", ("Training", "Hyperparameter")),
    Entry("Prompt", "Prompting", "The instructions and context supplied to a generative model.", "A prompt asks for a concise summary aimed at executives.", ("System prompt", "Few-shot prompting")),
    Entry("Prompt Injection", "Security", "An input designed to make a model ignore instructions or misuse connected tools and data.", "A malicious document tells a reading agent to reveal private context.", ("Guardrails", "System prompt")),
    Entry("Quantization", "Operations", "Representing model numbers with fewer bits to reduce memory use and often speed inference.", "An 8-bit model runs on hardware that cannot fit the full-precision version.", ("Distillation", "Inference")),
    Entry("RAG", "Retrieval", "Retrieval-Augmented Generation: fetching relevant sources and giving them to a model before it answers.", "A chatbot retrieves policy passages before answering an employee.", ("Embedding", "Vector database", "Grounding")),
    Entry("Reinforcement Learning", "Training", "Learning actions through rewards or penalties received from an environment.", "A game-playing system improves by receiving rewards for winning.", ("RLHF", "Agent")),
    Entry("RLHF", "Training", "Reinforcement Learning from Human Feedback, using human preferences to improve model behavior.", "Reviewers rank responses and the rankings guide further training.", ("Alignment", "Reinforcement learning")),
    Entry("Semantic Search", "Retrieval", "Search based on meaning rather than only exact keyword matches.", "A search for 'reset login' also finds a passage about changing a password.", ("Embedding", "Vector database")),
    Entry("Structured Output", "Prompting", "Model output constrained to a defined format such as a JSON schema.", "An extraction workflow returns validated fields instead of prose.", ("Tool use", "Prompt")),
    Entry("System Prompt", "Prompting", "High-priority instructions that define a model's role, boundaries, and behavior.", "A system prompt tells an assistant to answer using company policy only.", ("Prompt", "Prompt injection")),
    Entry("Temperature", "Prompting", "A setting that controls randomness in generated output; lower values are usually more predictable.", "A low temperature is useful for consistent data extraction.", ("Sampling", "Token")),
    Entry("Token", "Models", "A small unit of text processed by a language model, often a word or part of a word.", "The word 'unhelpful' may be split into multiple tokens.", ("Context window", "LLM")),
    Entry("Tool Use", "Agents", "A model's ability to call external functions, APIs, or applications through defined interfaces.", "An assistant calls a weather API before answering a forecast question.", ("Agent", "Structured output")),
    Entry("Transformer", "Models", "A neural network architecture built around attention and used by most modern language models.", "A transformer processes relationships among all tokens in a sentence.", ("Attention", "LLM")),
    Entry("Vector Database", "Retrieval", "A database optimized to store embeddings and find nearby vectors.", "A RAG system uses one to retrieve semantically similar passages.", ("Embedding", "RAG")),
    Entry("Zero-shot", "Prompting", "Asking a model to perform a task without providing examples in the prompt.", "A model classifies sentiment from instructions alone.", ("Few-shot prompting", "Prompt")),
)


_ENRICHMENTS: dict[str, tuple[tuple[str, ...], str]] = {
    "Artificial General Intelligence (AGI)": (("AGI",), "AGI is a research goal, not a capability current systems are known to possess."),
    "Generative AI": (("GenAI",), "It shifts AI from prediction toward creating new content."),
    "Large Language Model (LLM)": (("LLM",), "LLMs are the core model behind most modern chat and coding assistants."),
    "LoRA": (("Low-Rank Adaptation",), "LoRA makes model customization cheaper and more practical."),
    "Machine Learning": (("ML",), "Most modern AI systems are built using machine-learning techniques."),
    "Multimodal": ((), "Multimodal models can work across richer real-world inputs than text alone."),
    "Parameter": (("Weight",), "Parameter count is one rough indicator of a model's size and capacity."),
    "RAG": (("Retrieval-Augmented Generation",), "RAG uses fresh or private knowledge without retraining the base model."),
    "Reinforcement Learning": (("RL",), "Rewards are useful when behavior must be shaped by outcomes rather than labels alone."),
    "RLHF": (("Reinforcement Learning from Human Feedback",), "RLHF uses human preferences to make assistant behavior more useful."),
    "Token": ((), "Model limits and pricing are often measured in tokens rather than words."),
    "Zero-shot": (("Zero-shot Prompting",), "It tests whether a model understands a task from instructions alone."),
    "Chain of Thought": (("Chain-of-Thought Prompting", "CoT"), "Breaking complex problems into steps can improve reasoning performance."),
}

ENTRIES = tuple(
    Entry(
        entry.term,
        entry.category,
        entry.meaning,
        entry.example,
        entry.related,
        _ENRICHMENTS.get(entry.term, (entry.aliases, entry.why_it_matters))[0],
        _ENRICHMENTS.get(entry.term, (entry.aliases, entry.why_it_matters))[1],
    )
    for entry in ENTRIES
) + (
    Entry("Artificial Intelligence", "Foundations", "Software that performs tasks that normally require human intelligence.", "A system identifies objects in photos or writes a summary.", ("Machine Learning", "Generative AI"), ("AI",), "It is the broad umbrella containing modern machine learning and generative AI."),
    Entry("Deep Learning", "Foundations", "Machine learning based on large multi-layer neural networks.", "A deep network learns to recognize speech from thousands of hours of audio.", ("Neural Network", "Transformer"), (), "Deep learning powers most modern language, vision, and speech models."),
    Entry("Hyperparameter", "Models", "A setting chosen by developers rather than learned directly from data.", "Learning rate and batch size are hyperparameters.", ("Learning Rate", "Batch"), (), "Hyperparameters strongly affect training quality, speed, and cost."),
    Entry("Latent Space", "Models", "A compressed internal representation where useful features are encoded numerically.", "An image model moves through latent space to vary pose or style.", ("Embedding", "Diffusion Model"), (), "Latent representations let models manipulate complex concepts efficiently."),
    Entry("Vision-Language Model", "Models", "A model designed to understand both images and language.", "It inspects a screenshot and identifies the visible button.", ("Multimodal", "Transformer"), ("VLM",), "VLMs enable visual assistants, document understanding, and image reasoning."),
    Entry("Mixture of Experts", "Models", "A model with specialized subnetworks where only some activate for each input.", "A request routes through experts strongest at code or mathematics.", ("Transformer", "Parameter"), ("MoE",), "MoE increases capacity without using every parameter for every request."),
    Entry("Small Language Model", "Models", "A compact language model optimized for lower cost or local use.", "A laptop runs a small model offline for document classification.", ("Large Language Model (LLM)", "Quantization"), ("SLM",), "Small models help when privacy, latency, or device constraints matter."),
    Entry("Reasoning Model", "Models", "A model optimized for multi-step problems and complex decisions.", "It works through constraints before proposing a software architecture.", ("Large Language Model (LLM)", "Evaluation"), (), "Reasoning-oriented models improve planning, coding, and mathematics."),
    Entry("Training", "Training", "The process of adjusting model parameters using data so useful patterns are learned.", "A classifier learns from labeled examples of spam and normal email.", ("Loss Function", "Gradient Descent"), (), "Training is how a model acquires its capabilities."),
    Entry("Pretraining", "Training", "Large-scale initial training that gives a model broad general capabilities.", "An LLM learns language patterns before specialization.", ("Foundation Model", "Fine-tuning"), (), "Pretraining creates the reusable base for downstream applications."),
    Entry("PEFT", "Training", "Parameter-Efficient Fine-Tuning adapts a model while changing few parameters.", "LoRA updates small added matrices instead of the full model.", ("LoRA", "Fine-tuning"), ("Parameter-Efficient Fine-Tuning",), "PEFT reduces compute and storage requirements for customization."),
    Entry("Batch", "Training", "A group of examples processed together before a model update.", "A batch size of 32 processes 32 examples per optimization step.", ("Epoch", "Training"), (), "Batch size affects memory use, speed, and optimization behavior."),
    Entry("DPO", "Training", "Direct Preference Optimization trains directly from preferred and rejected responses.", "A model learns that reviewers prefer answer A over answer B.", ("RLHF", "Alignment"), ("Direct Preference Optimization",), "DPO simplifies some preference-training pipelines."),
    Entry("Top-p", "Prompting", "A sampling setting limiting choices to likely tokens whose probability reaches a threshold.", "A lower top-p generally makes output more conservative.", ("Temperature",), ("Nucleus Sampling",), "Top-p controls generation diversity."),
    Entry("Context Engineering", "Prompting", "Designing the complete information environment supplied to a model.", "An agent receives instructions, tools, retrieved documents, memory, and task state.", ("Prompt", "Context Window"), (), "For complex systems, context design matters as much as prompt wording."),
    Entry("Grounding", "Retrieval", "Connecting model answers to trusted evidence or data.", "A policy assistant cites retrieved handbook passages.", ("RAG", "Hallucination"), (), "Grounding reduces unsupported answers and makes outputs verifiable."),
    Entry("Hybrid Search", "Retrieval", "Combining semantic vector search with traditional keyword search.", "A system uses embeddings and exact product-code matches.", ("Semantic Search", "RAG"), (), "Hybrid search works well when meaning and exact terms both matter."),
    Entry("Reranker", "Retrieval", "A model that reorders retrieved results by relevance.", "Twenty passages are retrieved, then a reranker selects the best five.", ("RAG", "Hybrid Search"), (), "Reranking improves the context ultimately sent to the model."),
    Entry("Tool Calling", "Agents", "The structured mechanism by which a model requests an external action.", "The model requests search_orders with a customer argument.", ("Tool Use", "Structured Output"), ("Function Calling",), "Tool calls are a security boundary because output can trigger actions."),
    Entry("MCP", "Agents", "Model Context Protocol: a standard for connecting AI applications to tools and data.", "A coding assistant connects to GitHub and a database through MCP servers.", ("Agent", "Tool Use", "MCP Poisoning"), ("Model Context Protocol",), "MCP simplifies integrations while expanding an agent's trust boundary."),
    Entry("Planning", "Agents", "Breaking a larger goal into smaller steps before or during execution.", "An agent plans to inspect, edit, test, and submit a change.", ("Agent", "Reasoning Model"), (), "Planning helps agents complete dependent, multi-step tasks."),
    Entry("Agent Memory", "Agents", "Information retained across steps or sessions to maintain context.", "A research agent remembers which papers it reviewed.", ("Agent", "Context Engineering"), ("Memory",), "Memory improves continuity but persistent malicious data adds risk."),
    Entry("Human-in-the-loop", "Agents", "A design where a person reviews or approves important AI actions.", "An agent drafts a bank transfer but a human approves it.", ("Agent", "Guardrails"), ("HITL",), "Human approval limits the impact of mistakes or compromised agents."),
    Entry("Multi-agent System", "Agents", "A system where multiple AI agents cooperate or specialize.", "One agent researches while another verifies sources.", ("Agent", "Planning"), (), "Specialization adds capability along with coordination and security complexity."),
    Entry("Indirect Prompt Injection", "Security", "Prompt injection hidden in content the AI reads rather than direct user input.", "A webpage tells a browsing agent to send secrets elsewhere.", ("Prompt Injection", "RAG Poisoning"), (), "Agents routinely read untrusted content, making this a major risk."),
    Entry("Jailbreak", "Security", "A technique intended to bypass a model's safety or policy restrictions.", "A prohibited request is disguised inside elaborate role-play.", ("Prompt Injection", "Guardrails"), (), "Jailbreak testing measures how well model safeguards hold up."),
    Entry("Tool Poisoning", "Security", "Manipulating tool descriptions or outputs so an agent behaves unsafely.", "A malicious tool description tells the model to include credentials.", ("MCP Poisoning", "Agent"), (), "Agents often trust tool metadata, creating a new attack surface."),
    Entry("MCP Poisoning", "Security", "Using a malicious or compromised MCP server to influence an agent or steal data.", "A server advertises a useful tool but injects hidden instructions.", ("MCP", "Tool Poisoning"), (), "MCP servers are part of the AI software supply chain."),
    Entry("RAG Poisoning", "Security", "Planting malicious or misleading documents in a retrieval source.", "An attacker adds a document instructing an assistant to ignore policy.", ("RAG", "Indirect Prompt Injection"), (), "Retrieval needs provenance controls to resist attacker-controlled content."),
    Entry("Slopsquatting", "Security", "Registering a package name that an AI has hallucinated so later installs run malicious code.", "An assistant invents a dependency and an attacker publishes it.", ("Hallucination", "Supply-chain Security"), (), "Hallucinated dependencies can become software supply-chain attacks."),
    Entry("Data Exfiltration", "Security", "Unauthorized movement of sensitive information out of a trusted environment.", "A compromised agent posts API keys to an attacker endpoint.", ("Prompt Injection", "Least Privilege"), (), "Tool-enabled agents may be able to move sensitive data."),
    Entry("Least Privilege", "Security", "Giving an AI or tool only the minimum permissions needed.", "A documentation bot reads files but cannot delete repositories.", ("Agent", "Sandboxing"), (), "Least privilege limits damage from mistakes or manipulation."),
    Entry("Sandboxing", "Security", "Running code or tools in a restricted environment to limit damage.", "Generated Python runs without access to production credentials.", ("Least Privilege", "Agent"), (), "Sandboxing bounds potentially unsafe generated actions."),
    Entry("Supply-chain Security", "Security", "Protecting models, packages, datasets, tools, and dependencies from tampering.", "A team verifies package provenance before an agent installs it.", ("Slopsquatting", "Model Provenance"), (), "Each external AI component can introduce risk."),
    Entry("Model Provenance", "Security", "Information showing where a model came from and how it was produced.", "A company verifies publisher, checksum, license, and lineage.", ("Supply-chain Security", "AI Governance"), (), "Provenance helps organizations decide whether an artifact is trustworthy."),
    Entry("Model Theft", "Security", "Stealing a model's parameters, behavior, or proprietary capabilities.", "An attacker sends many queries to reproduce a commercial model.", ("Model",), (), "Models can represent major intellectual property investments."),
    Entry("Adversarial Example", "Security", "An intentionally modified input that causes a model to produce the wrong result.", "Tiny image changes make a classifier misread a stop sign.", ("Red Teaming", "Robustness"), (), "Adversarial examples reveal weaknesses ordinary testing may miss."),
    Entry("Red Teaming", "Security", "Actively attacking an AI system to find weaknesses before real attackers do.", "Testers attempt prompt injection, tool abuse, and data leakage.", ("Evaluation", "Guardrails"), (), "Red teaming covers failure modes beyond functional evaluation."),
    Entry("Metric", "Evaluation", "A numerical measure used to evaluate performance.", "Accuracy is the percentage of predictions that are correct.", ("Precision", "Recall"), (), "Metrics turn model behavior into measurable engineering targets."),
    Entry("Precision", "Evaluation", "Of items predicted positive, the fraction that were actually positive.", "If 80 of 100 flagged emails are spam, precision is 80%.", ("Recall", "F1 Score"), (), "Precision matters when false alarms are costly."),
    Entry("Recall", "Evaluation", "Of all real positive items, the fraction the model found.", "If 80 of 100 spam emails are detected, recall is 80%.", ("Precision", "F1 Score"), (), "Recall matters when missing a true case is costly."),
    Entry("F1 Score", "Evaluation", "A single score balancing precision and recall.", "It helps when missed positives and false alarms both matter.", ("Precision", "Recall"), (), "F1 is useful when accuracy hides class imbalance."),
    Entry("Perplexity", "Evaluation", "A measure of how surprised a language model is by text; lower is generally better.", "Lower perplexity means the next tokens are predicted more confidently.", ("Large Language Model (LLM)", "Evaluation"), (), "It measures prediction, not usefulness or safety."),
    Entry("Robustness", "Evaluation", "How reliably a model performs on noisy, unusual, or adversarial inputs.", "A robust vision model still works when lighting changes.", ("Adversarial Example", "Evaluation"), (), "Production systems must work beyond ideal benchmark conditions."),
    Entry("Throughput", "Operations", "How much work a system can process over time.", "A serving cluster handles 2,000 requests per minute.", ("Latency", "Inference"), (), "Throughput determines how well an AI service scales."),
    Entry("GPU", "Operations", "A highly parallel processor widely used for AI workloads.", "Training a large transformer may use hundreds of GPUs.", ("Training", "Inference"), ("Graphics Processing Unit",), "GPU availability and cost constrain modern AI infrastructure."),
    Entry("NPU", "Operations", "A processor optimized specifically for neural-network operations.", "A laptop NPU runs speech recognition without heavily using the CPU.", ("Inference", "Edge AI"), ("Neural Processing Unit",), "NPUs make local AI practical on phones and PCs."),
    Entry("Edge AI", "Operations", "Running AI models locally on devices instead of relying entirely on cloud servers.", "A phone recognizes an image without uploading it.", ("NPU", "Small Language Model"), (), "Edge AI improves privacy, latency, and offline capability."),
    Entry("Caching", "Operations", "Reusing computed results to reduce latency and cost.", "A repeated embedding request is served from cache.", ("Latency", "Inference"), (), "Caching substantially reduces repeated model work."),
    Entry("Prompt Caching", "Operations", "Reusing computation for repeated prompt prefixes or context.", "A shared long system prompt is processed once and reused.", ("Caching", "Context Window"), (), "Prompt caching lowers cost and latency for repeated context."),
    Entry("Observability", "Operations", "Collecting traces, metrics, logs, and events to understand system behavior.", "A dashboard shows failed tool calls and agent latency.", ("Tracing", "Evaluation"), (), "Production visibility matters because AI behavior is probabilistic."),
    Entry("Tracing", "Operations", "Recording the sequence of steps taken by an AI workflow or agent.", "A trace shows prompt -> retrieval -> model -> tool call -> response.", ("Observability", "Agent"), (), "Tracing makes complex agent failures easier to diagnose."),
    Entry("AI Gateway", "Operations", "A control layer handling routing, policy, logging, or security between apps and models.", "All model requests pass through one monitored gateway.", ("Observability", "Guardrails"), (), "A gateway centralizes controls across models and applications."),
    Entry("Moderation", "Governance", "Detecting or filtering content according to safety or platform policies.", "A moderation model flags abusive content before publication.", ("Guardrails", "Policy"), (), "Moderation is one component of broader AI governance."),
    Entry("AI Governance", "Governance", "Processes and controls for managing AI risk, accountability, and acceptable use.", "A company requires review before AI handles customer data.", ("Policy", "Model Provenance"), (), "Governance connects technical systems to organizational accountability."),
    Entry("Model Card", "Governance", "Documentation of a model's intended use, limits, evaluations, and risks.", "A model card states supported languages and known gaps.", ("AI Governance", "Evaluation"), (), "Model cards clarify when a model is appropriate."),
    Entry("Policy", "Governance", "A rule defining what an AI system, user, or organization may do.", "Company policy prohibits customer data in unapproved models.", ("Guardrails", "AI Governance"), (), "Policies become enforceable requirements for controls and workflows."),
    Entry("Evaluation", "Evaluation", "Measuring how well an AI system performs against defined criteria.", "A team tests factual accuracy, latency, safety, and tool success before deployment.", ("Benchmark", "Metric"), ("Eval", "Evals"), "Good evaluation is essential before trusting an AI system in production."),
    Entry("Narrow AI", "Foundations", "AI designed for a specific task or limited domain rather than general intelligence.", "A fraud detector identifies suspicious payments but cannot plan a holiday.", ("Artificial General Intelligence (AGI)", "Machine Learning"), ("Weak AI",), "All widely deployed AI today is narrow, even when it handles several related tasks."),
    Entry("Regularization", "Training", "Techniques that discourage a model from fitting training data too specifically.", "Weight decay penalizes overly large model parameters during training.", ("Overfitting", "Validation Set"), (), "Regularization helps models generalize to unseen data."),
    Entry("Sampling", "Prompting", "Selecting generated tokens from the model's probability distribution.", "Temperature and top-p adjust which possible next words can be selected.", ("Temperature", "Top-p"), (), "Sampling controls the balance between predictable and varied output."),
    Entry("Supervised Learning", "Foundations", "Learning from examples paired with known labels or desired outputs.", "A classifier learns from emails labeled spam or not spam.", ("Machine Learning", "Training"), (), "Supervised learning is a common way to train reliable task-specific models."),
    Entry("Validation Set", "Training", "Data held out from training and used to tune choices and detect overfitting.", "A team compares checkpoints on validation examples before final testing.", ("Overfitting", "Regularization"), (), "Validation gives an early signal of whether a model generalizes."),
    Entry("Algorithm", "Foundations", "A step-by-step procedure for solving a problem or completing a task.", "A sorting algorithm arranges numbers from smallest to largest.", ("Machine Learning",), (), "Algorithms are the building blocks of all computing and AI."),
    Entry("Computer Vision", "Foundations", "A field of AI that enables computers to see and understand images and videos.", "A system identifies objects, faces, or text from photographs.", ("Deep Learning", "Neural Network"), (), "Computer vision powers autonomous vehicles, medical imaging, and surveillance."),
    Entry("Natural Language Processing", "Foundations", "A branch of AI focused on enabling machines to understand and generate human language.", "An NLP system translates text, answers questions, or analyzes sentiment.", ("Transformer", "Large Language Model (LLM)"), ("NLP",), "NLP connects human language to machine reasoning and is central to chatbots and search."),
    Entry("Robotics", "Foundations", "The field combining engineering and AI to design and build machines capable of physical tasks.", "A robot arm in a factory assembles parts with precision.", ("Agent", "Machine Learning"), (), "Robotics bridges the gap between AI decision-making and real-world action."),
    Entry("Artificial Superintelligence", "Foundations", "A hypothetical AI capable of surpassing human intelligence in every domain.", "ASI is theoretical and raises profound questions about control and alignment.", ("Artificial General Intelligence (AGI)",), ("ASI",), "ASI remains speculative but important to discussions about long-term AI safety."),
    Entry("Artificial Narrow Intelligence", "Foundations", "AI designed to perform a specific task or narrow set of functions.", "A chess engine plays chess better than humans but cannot translate languages.", ("Narrow AI",), ("ANI", "Weak AI"), "All current AI systems are narrow, excelling at defined tasks but lacking general reasoning."),
    Entry("AI Safety", "Security", "The field focused on ensuring AI systems behave reliably and do not cause harm.", "Safety research addresses both technical failures and intentional misuse.", ("Alignment", "Guardrails"), (), "AI Safety becomes more critical as systems gain autonomy and control over important decisions."),
    Entry("Bias in AI", "Security", "Systematic errors or prejudices that favor certain groups or perspectives in AI outputs.", "A hiring model may discriminate against women if trained on biased historical data.", ("Fairness", "Alignment"), ("AI Bias",), "Bias can reflect and amplify human prejudice, making detection and correction essential."),
    Entry("Explainable AI", "Security", "AI systems designed to be transparent so humans understand their decisions and reasoning.", "A loan-denial system explains which factors led to rejection.", ("Interpretability", "Guardrails"), ("XAI",), "Explainability is required for regulated decisions and helps build trust."),
    Entry("Interpretability", "Security", "The degree to which humans can understand how an AI system arrives at its decisions.", "A doctor wants to know which symptoms an AI used to recommend a diagnosis.", ("Explainable AI",), (), "Interpretability is especially important in high-stakes domains like medicine and justice."),
    Entry("Responsible AI", "Governance", "Frameworks and practices guiding the ethical, transparent, and accountable development of AI.", "A company establishes processes for auditing, documenting, and testing models before deployment.", ("AI Governance", "Ethical AI", "Alignment"), (), "Responsible AI treats safety, fairness, privacy, and transparency as design principles."),
    Entry("Ethical AI", "Governance", "AI design and deployment aligned with human values, fairness, and societal well-being.", "An AI system is built to avoid discrimination and respect user privacy.", ("Responsible AI", "Alignment"), (), "Ethical AI requires ongoing dialogue between technologists, ethicists, and affected communities."),
    Entry("AI Fluency", "Governance", "The capacity to collaborate productively with AI by understanding its capabilities, limits, and implications.", "A business manager knows when to trust AI recommendations and when to seek human review.", ("Human-Centered AI",), (), "AI fluency is becoming as essential as digital literacy in the modern workplace."),
    Entry("Human-Centered AI", "Governance", "An approach to AI that prioritizes human needs, autonomy, and well-being throughout development.", "A design team involves end users early to ensure the AI assistant fits their workflow.", ("Responsible AI", "Human-in-the-loop"), (), "Human-centered AI emphasizes humans directing AI rather than AI replacing human judgment."),
    Entry("Bias", "Security", "Statistical error or systematic prejudice in a model, often caused by training data or algorithm design.", "A credit model may undervalue women's income, leading to unfair loan denials.", ("Fairness", "Bias in AI"), (), "Mitigating bias requires examining data provenance, model behavior, and decision outcomes."),
    Entry("Fairness", "Security", "Ensuring AI systems treat individuals and groups equitably without discrimination.", "A hiring system gives equal consideration regardless of demographic background.", ("Bias", "Responsible AI"), (), "Fairness is context-dependent and requires explicit definition based on domain and values."),
    Entry("Unsupervised Learning", "Training", "Machine learning where models are trained on unlabeled data to discover patterns.", "A system groups customer transactions into spending categories without being told what categories exist.", ("Machine Learning", "Clustering"), (), "Unsupervised learning is useful for exploratory analysis and finding hidden structure."),
    Entry("Self-Supervised Learning", "Training", "Training where a model creates its own supervision signal from raw data.", "A model predicts masked words in sentences, learning language patterns without explicit labels.", ("Pretraining", "Transfer Learning"), (), "Self-supervised learning is how foundation models learn broad capabilities at scale."),
    Entry("Transfer Learning", "Training", "Reusing knowledge learned on one task to improve performance on a related task.", "A model trained on general images transfers to medical image analysis with minimal retraining.", ("Foundation Model", "Fine-tuning"), (), "Transfer learning dramatically reduces the data and compute needed for new applications."),
    Entry("Federated Learning", "Training", "Training a model across decentralized devices while data remains local.", "A keyboard predicts next words on your phone without sending typing data to servers.", ("Privacy", "Machine Learning"), (), "Federated learning enables privacy-preserving model improvement across distributed users."),
    Entry("Contrastive Learning", "Training", "A technique where models learn by comparing similar and dissimilar examples.", "A model learns that images of the same cat are similar but different from images of dogs.", ("Self-Supervised Learning", "Representation Learning"), (), "Contrastive learning is efficient at learning useful feature representations."),
    Entry("Data Augmentation", "Training", "Artificially expanding a training dataset by creating modified versions of existing examples.", "Rotating, cropping, and color-shifting images to teach a model robustness.", ("Training Data", "Overfitting"), (), "Data augmentation improves generalization and reduces overfitting without collecting new data."),
    Entry("Prompt Engineering", "Prompting", "The practice of carefully designing inputs to guide generative models toward desired outputs.", "Instead of 'Explain AI', a more precise prompt is 'Explain AI in three sentences for a 10-year-old.'", ("Prompt", "Context Engineering"), (), "Prompt engineering bridges user intent and model capability, often with surprising specificity."),
    Entry("Few-Shot Learning", "Training", "Machine learning where models learn new tasks from a small number of labeled examples.", "A classifier learns to recognize a new handwritten digit from only five examples.", ("Transfer Learning", "Fine-tuning"), (), "Few-shot learning measures a model's ability to generalize from minimal data."),
    Entry("Zero-Shot Learning", "Training", "AI performing tasks without explicit training examples, using only semantic knowledge.", "A model recognizes an animal it has never seen by understanding that it has 'four legs' and 'brown fur.'", ("Transfer Learning",), (), "Zero-shot learning requires models to generalize from descriptions and learned concepts."),
    Entry("Tokenization", "Models", "Breaking text into tokens (words, subwords, or characters) that AI models process.", "'Hello' becomes ['He', 'llo'] or ['H', 'e', 'l', 'l', 'o'] depending on the tokenizer.", ("Token", "Large Language Model (LLM)"), (), "Tokenization affects model efficiency, cost, and how language is represented."),
    Entry("Generative Adversarial Network", "Models", "A model architecture with two competing networks: a generator creating data and a discriminator judging it.", "A GAN learns to create realistic images by having a generator fool a discriminator.", ("Diffusion Model", "Generative AI"), ("GAN",), "GANs are powerful for image generation but can be unstable to train."),
    Entry("Vision Transformer", "Models", "An adaptation of the transformer architecture designed to process and analyze images.", "A ViT divides an image into patches and attends to their relationships like an LLM attends to words.", ("Transformer", "Computer Vision"), ("ViT",), "Vision Transformers achieved state-of-the-art results and unified vision and language architectures."),
    Entry("Knowledge Graph", "Retrieval", "A structured database representing entities and their relationships as interconnected nodes.", "A knowledge graph stores that 'Paris is the capital of France' and links related facts.", ("RAG", "Semantic Search"), (), "Knowledge graphs enable rich semantic queries and can ground AI outputs in structured facts."),
    Entry("Tensor", "Models", "A multi-dimensional array of numbers; the fundamental data structure in neural networks.", "A 3D tensor stores an image as width × height × color channels.", ("Neural Network", "Deep Learning"), (), "All data flowing through neural networks is represented as tensors."),
    Entry("MLOps", "Operations", "Machine Learning Operations: practices for deploying, monitoring, and maintaining ML models in production.", "An MLOps team automates model retraining, monitors performance drift, and manages rollbacks.", ("Observability", "Model Drift"), ("Machine Learning Operations",), "MLOps is essential for reliable, scalable AI systems at scale."),
    Entry("LLMOps", "Operations", "Large Language Model Operations: managing the full lifecycle of LLM applications.", "An LLMOps team handles prompt versioning, output caching, and cost monitoring.", ("MLOps", "Observability"), ("Large Language Model Operations",), "LLMOps adds challenges around non-deterministic outputs and variable token costs."),
    Entry("Model Drift", "Operations", "Performance degradation when a model encounters real-world data that differs from training data.", "A loan-approval model trained in 2020 makes worse decisions in 2026 because economic conditions changed.", ("Training Data", "Monitoring"), (), "Detecting and responding to model drift is crucial for maintaining production reliability."),
    Entry("Training Data", "Training", "The collection of examples used to teach a machine learning model.", "A spam classifier is trained on thousands of labeled emails.", ("Training", "Data Augmentation"), (), "Training data quality directly impacts model performance; garbage in, garbage out."),
    Entry("Synthetic Data", "Training", "Artificially generated data created by algorithms rather than collected from real-world sources.", "A simulator generates thousands of traffic scenarios for training autonomous vehicles.", ("Data Augmentation", "Training Data"), (), "Synthetic data enables privacy-preserving training and addresses data scarcity."),
    Entry("Scaling Laws", "Foundations", "Predictable relationships between model size, training data, compute, and performance.", "Doubling model size or training data often improves performance by a predictable amount.", ("Foundation Model", "Training"), (), "Scaling laws guide investment in compute and data and help predict model capabilities."),
    Entry("Sentiment Analysis", "Retrieval", "Detecting and categorizing emotional tone in text.", "Analyzing reviews to determine if customer feedback is positive, negative, or neutral.", ("Natural Language Processing", "Classification"), (), "Sentiment analysis powers customer feedback analysis and social media monitoring."),
    Entry("Data Mining", "Training", "Discovering patterns and trends in large datasets using statistical and ML methods.", "Analyzing sales data to identify which products are frequently bought together.", ("Machine Learning", "Unsupervised Learning"), (), "Data mining uncovers actionable insights hidden in historical data."),
    Entry("Decision Tree", "Training", "A simple ML algorithm that makes predictions by asking yes/no questions recursively.", "'If age < 18, then high risk; else check credit score.'", ("Machine Learning", "Ensemble Methods"), (), "Decision trees are interpretable but prone to overfitting; often improved via ensemble methods."),
    Entry("Ensemble Methods", "Training", "Combining multiple models to produce better predictions than any single model.", "Random forests combine hundreds of decision trees to reduce overfitting.", ("Machine Learning", "Bagging"), (), "Ensembles are a practical way to improve robustness and accuracy."),
    Entry("k-Nearest Neighbors", "Training", "A simple ML algorithm that classifies based on the k closest training examples.", "To classify a new iris flower, find the three most similar irises in the training set.", ("Machine Learning", "Classification"), ("k-NN",), "k-NN is intuitive but slow on large datasets; useful for understanding ML basics."),
    Entry("Bayesian Network", "Training", "A graphical model representing probabilistic relationships between variables.", "A Bayesian network encodes how symptoms relate to diseases via conditional probabilities.", ("Probabilistic Model", "Machine Learning"), (), "Bayesian networks enable reasoning under uncertainty and are used in expert systems."),
    Entry("Dimensionality Reduction", "Training", "Reducing the number of features in data while preserving important information.", "Projecting high-dimensional image data onto two dimensions for visualization.", ("Feature Engineering", "Machine Learning"), (), "Dimensionality reduction improves interpretability and reduces computational cost."),
    Entry("Markov Chain", "Training", "A mathematical model where future states depend only on the current state, not history.", "Predicting tomorrow's weather based only on today's weather, not the full weather history.", ("Probabilistic Model", "Reinforcement Learning"), (), "Markov chains are used in language modeling, finance, and many stochastic systems."),
    Entry("Open-Weight Model", "Governance", "An AI model whose trained weights are publicly released for download and use.", "A company releases the weights of a language model so researchers can fine-tune it.", ("Open Source", "Foundation Model"), (), "Open-weight models accelerate research but raise questions about responsibility and misuse."),
    Entry("Open Source", "Governance", "Software whose source code is publicly available for viewing, modification, and redistribution.", "Anyone can inspect, improve, and redistribute an open-source ML library.", ("Closed Source", "Open-Weight Model"), (), "Open source enables community contribution and transparency but requires community maintenance."),
    Entry("Closed Source", "Governance", "Software whose source code is proprietary and not available for public inspection or modification.", "A commercial AI model's internal architecture and training process remain confidential.", ("Open Source",), (), "Closed source can protect intellectual property but reduces transparency and auditability."),
    Entry("Chatbot", "Applications", "Software designed to simulate conversation with humans via text or voice.", "A customer support chatbot answers FAQs and escalates complex issues to humans.", ("Conversational AI", "Natural Language Processing"), (), "Chatbots range from rule-based systems to large language models."),
    Entry("Conversational AI", "Applications", "AI systems that simulate natural, human-like dialogue and interaction.", "A virtual assistant understands context and maintains conversation state across multiple turns.", ("Chatbot", "Natural Language Processing"), (), "Conversational AI powers voice assistants, support bots, and dialogue-based applications."),
    Entry("Automation", "Applications", "Using AI and technology to perform tasks with minimal human intervention.", "Automating invoice processing, email filtering, or customer onboarding.", ("Agent", "Machine Learning"), (), "Automation improves efficiency but requires careful design to avoid unintended consequences."),
    Entry("Anthropomorphism", "Applications", "Attributing human traits, emotions, or intentions to non-human entities like AI.", "Saying an AI 'understands' or 'wants' something when it is just pattern-matching.", ("Human-Centered AI", "AI Fluency"), (), "Anthropomorphism can mislead users about AI capabilities; clarity is essential for responsible deployment."),
    Entry("Predictive Analytics", "Applications", "Using data and ML models to forecast future outcomes or trends.", "Predicting which customers are likely to churn so retention efforts can target them.", ("Machine Learning", "Data Mining"), (), "Predictive analytics drives business decisions from sales forecasting to risk assessment."),
    Entry("Feedback Loop", "Applications", "Using model outputs or results to improve the model's future performance.", "Customer corrections to chatbot responses are fed back to retrain and improve it.", ("Reinforcement Learning", "Observability"), (), "Feedback loops enable continuous improvement but can also amplify biases if not carefully managed."),
    Entry("Emergent Behavior", "Foundations", "Unexpected or novel patterns that arise from complex AI systems and their interactions with data.", "A language model exhibits reasoning skills not explicitly programmed into it.", ("Foundation Model", "Large Language Model (LLM)"), (), "Emergent abilities in large models suggest thresholds where new capabilities suddenly appear."),
    Entry("Big Data", "Foundations", "Extremely large datasets too massive for traditional data processing tools.", "Processing billions of social media posts to identify trends.", ("Data Mining", "Machine Learning"), (), "Big data enables pattern discovery at scale but poses storage, processing, and privacy challenges."),
    Entry("Zero Data Retention", "Security", "A privacy policy ensuring that user data is not stored or retained after processing.", "A voice assistant processes your command but immediately discards the audio.", ("Privacy", "Differential Privacy"), (), "Zero data retention protects privacy but complicates improving models from user interactions."),
    Entry("Differential Privacy", "Security", "A mathematical technique for querying datasets while protecting individual privacy.", "Publishing aggregate statistics without revealing whether a specific person is in the dataset.", ("Privacy", "Zero Data Retention"), (), "Differential privacy enables data analysis while providing formal privacy guarantees."),
    Entry("AI Toxicity", "Security", "Harmful, offensive, false, or inappropriate outputs generated by AI systems.", "A language model generates biased or hateful text due to patterns in training data.", ("Bias", "Alignment", "Guardrails"), (), "Mitigating toxicity requires careful data curation, red-teaming, and output filtering."),
    Entry("Agentic AI", "Agents", "AI systems designed to autonomously perceive goals, plan actions, and adapt over time.", "An AI agent reads customer emails, categorizes issues, and suggests responses.", ("Agent", "Reasoning Model"), (), "Agentic AI represents a shift toward autonomous systems rather than reactive tools."),
    Entry("Traditional AI", "Foundations", "Earlier AI approaches relying on explicit rules, logic, and human-defined knowledge.", "An expert system uses if-then rules to diagnose diseases.", ("Machine Learning", "Deep Learning"), (), "Traditional AI excels at structured reasoning; modern AI excels at pattern recognition from data."),
    Entry("Expert System", "Applications", "AI programs that mimic expert decision-making using knowledge bases and logical rules.", "A medical expert system helps diagnose diseases by encoding doctor knowledge.", ("Traditional AI", "Knowledge Graph"), (), "Expert systems dominated early AI and are still useful for well-structured domains."),
    Entry("Human-Computer Interaction", "Applications", "The process of how people interact with computer systems.", "Designing a user interface so people can easily instruct an AI system.", ("Human-Centered AI", "Chatbot"), ("HCI",), "Good HCI design is essential for AI systems to be usable and trusted."),
    Entry("Turing Test", "Foundations", "A proposed measure of machine intelligence: can a machine exhibit behavior indistinguishable from a human?", "A text conversation where a judge cannot tell if they're talking to a human or AI.", (), (), "The Turing Test remains philosophical; passing it does not guarantee true understanding."),
    Entry("Representation Learning", "Training", "Learning compact, useful features or patterns from raw data automatically.", "A neural network learns to represent images as compact vectors capturing visual concepts.", ("Deep Learning", "Feature Engineering"), (), "Representation learning is how deep learning achieves high performance without manual feature engineering."),
    Entry("Feature Engineering", "Training", "Designing and selecting relevant features from raw data to improve model performance.", "Creating a 'days since last purchase' feature from transaction timestamps.", ("Training Data", "Representation Learning"), (), "Good features can be more important than the model choice itself."),
    Entry("Clustering", "Training", "Grouping similar examples together without labels, discovering natural structure.", "Grouping customers by purchasing behavior to identify market segments.", ("Unsupervised Learning", "Classification"), (), "Clustering reveals hidden patterns and can guide further investigation or decision-making."),
    Entry("Regression", "Training", "Predicting a continuous numerical value.", "Predicting house prices from features like square footage and location.", ("Supervised Learning", "Machine Learning"), (), "Regression complements classification for problems with continuous outputs."),
    Entry("Monitoring", "Operations", "Continuously observing AI system performance in production to detect issues.", "Tracking whether a fraud detector's accuracy remains above 95%.", ("Observability", "Model Drift"), (), "Monitoring enables early detection of performance degradation and biases in production."),
    Entry("Privacy", "Security", "Protecting sensitive user information from unauthorized access or exposure.", "A health AI model should not reveal which individuals are in its training data.", ("Differential Privacy", "Zero Data Retention"), (), "Privacy protection is both an ethical imperative and often a legal requirement."),
    Entry("AI Alignment", "Security", "Ensuring AI system goals and behavior match human values and intentions.", "Training a language model to be helpful and refuse harmful requests.", ("Alignment", "RLHF", "Guardrails"), (), "Alignment becomes more challenging as systems grow in power and autonomy."),
    Entry("Probabilistic Model", "Training", "A model that represents uncertainty explicitly through probability distributions.", "A Bayesian classifier outputs a probability of each class rather than a single prediction.", ("Machine Learning", "Bayesian Network"), (), "Probabilistic models enable reasoning under uncertainty and principled decision-making.")
)


def categories() -> tuple[str, ...]:
    return ("All",) + tuple(sorted({entry.category for entry in ENTRIES}))


def _searchable_text(entry: Entry) -> str:
    return " ".join(
        (
            entry.term,
            entry.category,
            entry.meaning,
            entry.example,
            entry.why_it_matters,
            *entry.aliases,
            *entry.related,
        )
    ).casefold()


def search(query: str = "", category: str = "All") -> list[Entry]:
    normalized_query = " ".join(query.casefold().split())
    words = tuple(normalized_query.split())
    matches: list[tuple[int, Entry]] = []

    for entry in ENTRIES:
        if category != "All" and entry.category != category:
            continue

        haystack = _searchable_text(entry)
        if not all(word in haystack for word in words):
            continue

        term = entry.term.casefold()
        aliases = tuple(alias.casefold() for alias in entry.aliases)
        score = 50 if term == normalized_query or normalized_query in aliases else 0
        for word in words:
            if term == word:
                score += 20
            elif term.startswith(word):
                score += 12
            elif word in term:
                score += 8
            elif any(alias == word for alias in aliases):
                score += 16
            elif any(alias.startswith(word) for alias in aliases):
                score += 10
            else:
                score += 1
        matches.append((score, entry))

    return [
        entry
        for _, entry in sorted(
            matches,
            key=lambda item: (-item[0], item[1].term),
        )
    ]


def get(term: str) -> Entry | None:
    needle = term.casefold().strip()
    for entry in ENTRIES:
        if entry.term.casefold() == needle:
            return entry
        if any(alias.casefold() == needle for alias in entry.aliases):
            return entry
    return None


def related_entries(entry: Entry) -> list[Entry]:
    return [match for name in entry.related if (match := get(name)) is not None]


def format_entry(entry: Entry) -> str:
    lines = [entry.term, f"Category: {entry.category}", "", entry.meaning, "", f"Example: {entry.example}"]
    if entry.why_it_matters:
        lines.extend(("", f"Why it matters: {entry.why_it_matters}"))
    if entry.related:
        lines.extend(("", "Related: " + ", ".join(entry.related)))
    return "\n".join(lines)


def browse(query: str = "", category: str = "All", limit: int = 20) -> Iterable[Entry]:
    return search(query, category)[: max(0, limit)]