from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from glossary import ENTRIES


OUTPUT_PATH = Path(__file__).with_name("web") / "glossary-data.js"


def main() -> None:
    entries = [asdict(entry) for entry in ENTRIES]
    payload = json.dumps(entries, ensure_ascii=True, indent=2)
    OUTPUT_PATH.parent.mkdir(exist_ok=True)
    OUTPUT_PATH.write_text(
        "// Generated by export_web_data.py. Do not edit directly.\n"
        f"window.GLOSSARY_ENTRIES = {payload};\n",
        encoding="utf-8",
    )
    print(f"Exported {len(entries)} entries to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()